### ISSUE TITLE
LOG_LEVEL

### ISSUE THREAD

**Issue by VortexMashiro** [ArtificialQualia/PELD-Server#1]
LOG_LEVEL not found in config.py lol
https://imgur.com/a/SpGAr5q

**Comment by ArtificialQualia** [comment]
Whoops!  That's what I get for leaving my config file untracked.

I've commited the missing setting (and import statement), you can pull the latest commit or just modify your config yourself.

**Comment by VortexMashiro** [comment]
That would be nice :D,btw thx for the amazing project.

**Comment by ArtificialQualia** [comment]
No problem, and if you encounter any issues with the deployment wiki page let me know so I can update it.
