### ISSUE TITLE
DPS graph of the fleet

### ISSUE THREAD

**Issue by NormannK** [ArtificialQualia/PELD-Server#2]
It would be great to see a graph of the dps for the whole fleet and not only for one char.
Everybody in fleet should be able to see the graph.

That feature would be great for eve streamers.

**Comment by ArtificialQualia** [comment]
Have you checked out [peld-fleet.com](peld-fleet.com)?  Through that site, an FC can get a view of all the members of a fleet that have PELD connected.  It is limited to FCs for opsec reasons and to allow for additional fleet management through the site.

**Comment by ArtificialQualia** [comment]
The site is limited to FCs for opsec reasons and to enable additional fleet management capabilities.  It would be possible to open up the actual DPS numbers to others, but allowing that should at the very least be controllable by the FC and I'm not entirely sure how useful it is for line members to see each other's DPS, but I could see how they might find it interesting.

I considered having graphing on the site, but with anything more than a couple fleet members the graph would be very difficult to read and not provide easily actionable information which is critical while you are in combat.

**Comment by NormannK** [comment]
Thanks for the response! Initially we thought about steaming a graph of the fleet dps live.
You might saw the stream of pando (https://www.twitch.tv/zehpando)

We even thought about making the FC overview public to all fleet member! so the fleet moral is boosted to gain higher DPS on the target. 

Discussing the overview with Pando: we think its to complicated for the FC to FC the fleet and watching the overview. A simple graph like the local dps graph for the whole fleet would be great!

Since I'm proposing several thinks here, how about a meeting in a voice tool with our group? We'd really like to use your tool on big fleets with streaming on twitch.

**Comment by ArtificialQualia** [comment]
Sure, I'm open to a larger conversation.  I'm aware of a few streamers that are using the local graphing, but didn't know Pando was using PELD.  I've joined Pando's discord so that we can coordinate.
